src-git packages https://git.openwrt.org/feed/packages.git^1302d3e88aacb698fdec91b5fb2de3bcbbe56509
src-git luci https://git.openwrt.org/project/luci.git^f7e59912304972e500fa6caf63d925c671b26cb6
src-git routing https://git.openwrt.org/feed/routing.git^8c2385009d29a6d4e3ecc8cc38e8c5c0d71c691f
src-git telephony https://git.openwrt.org/feed/telephony.git^4d8d33a023b24c52cd9443b9dc201fbdfe9c6aef
src-git video https://github.com/openwrt/video.git^a951381b6c58b9b1eb087f09c9a20cff4ffe8063

