#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034

START=22
STOP=89
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/xg040g-autoip-monitor
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger xg040g-management network
}
