#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034

START=51
STOP=49
USE_PROCD=1

start_service() {
	mkdir -p /mnt/kvmstore/netboot

	procd_open_instance
	procd_set_param command /usr/sbin/uhttpd \
		-f -h /mnt/kvmstore/netboot -p 10.40.0.1:8081 \
		-n 3 -N 20 -A 1 -D
	procd_set_param respawn 3600 5 5
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger xg040g-management
	procd_add_raw_trigger "interface.pxe.up" 1000 /etc/init.d/xg040g-pxe-http restart
}
