#!/bin/sh

uci -q batch <<-'EOF'
	set luci_statistics.collectd_thermal=statistics
	set luci_statistics.collectd_thermal.enable='1'
	set luci_statistics.collectd_thermal.IgnoreSelected='0'
	set luci_statistics.collectd_thermal.Device=''
	set luci_statistics.collectd_rrdtool.DataDir='/tmp/rrd'
	set luci_statistics.collectd_rrdtool.backup='0'
	commit luci_statistics
EOF

exit 0
