#!/bin/sh

uci -q delete luci_statistics.collectd_interface.Interfaces || true

uci -q batch <<-'EOF'
	add_list luci_statistics.collectd_interface.Interfaces='br-lan'
	add_list luci_statistics.collectd_interface.Interfaces='br-pxe'
	add_list luci_statistics.collectd_interface.Interfaces='eth1'
	add_list luci_statistics.collectd_interface.Interfaces='lan2'
	add_list luci_statistics.collectd_interface.Interfaces='lan3'
	add_list luci_statistics.collectd_interface.Interfaces='lan4'
	set luci_statistics.collectd_interface.IgnoreSelected='0'
	set luci_statistics.collectd_thermal=statistics
	set luci_statistics.collectd_thermal.enable='1'
	set luci_statistics.collectd_thermal.IgnoreSelected='0'
	set luci_statistics.collectd_thermal.Device=''
	set luci_statistics.collectd_rrdtool.DataDir='/tmp/rrd'
	set luci_statistics.collectd_rrdtool.backup='0'
	commit luci_statistics
EOF

exit 0
